apiVersion: v1
kind: Service
metadata:
  name: firebase-service
spec:
  selector:
    app: firebase
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP  # Internal service
